#!/bin/bash

block (){
	echo "------------------------------------------"
	echo "##########################################"
	echo "------------------------------------------"
}

#Update System
block
echo "Updating System"
sudo apt update -y
echo "Complete"

#Check or create for noah-adm user
echo "Checking for user noah-adm"

if [ -d "/home/noah-adm" ]; then
	echo "User exists"
else
	echo "User does not exist: Creating User"
	sudo adduser noah-adm
	sudo usermod -aG sudo noah-adm
fi

#Install Git
block
if [[ $(command -v git) ]]; then
	echo "Git is Already installed, Moving On"
else
	echo "Installing Git"
	sudo apt install git -y
fi
echo "Complete"

#Install Nginx
block
if [[ $(command -v nginx) ]]; then
	echo "Nginx is Already installed, Moving On"
else
	echo "Installing Nginx"
	sudo apt install nginx -y
fi
echo "Complete"

#Download Repo
block
echo "Downloading Class Repo"

git -C /home/noah-adm/Documents/ clone https://github.com/CyPH3RSkULL5/TechNotes.git

echo "Complete"

#Check Hostname
block
echo "hostname is: " $(hostname) 
echo "---"

if [ "$(hostname)" = "nginx01-noah" ]; then
	echo "Hostname Is Correct, Moving on"
else
	echo "hostname incorrect setting"
	hostnamectl set-hostname nginx01-noah
	echo "New Hostname Set"
fi

block

#Copy Nginx Configs from downloaded Repo
echo "Making website directory"
echo
sudo mkdir /var/www/website
echo "Copying Index.html"
echo
cp /home/noah-adm/Documents/Technotes/SEC-350/index.html /var/www/website
echo "Restarting Service"
sudo service nginx restart

echo $(systemctl status nginx | grep Active)
echo "Complete"

block


