#!/bin/bash

block (){
	echo "------------------------------------------"
	echo "##########################################"
	echo "------------------------------------------"
}

#Update System
block
echo "Updating System"
sudo apt update -y
echo "Complete"

#Check or create for noah-adm user
echo "Checking for user noah-adm"

if [ -d "/home/noah-adm" ]; then
	echo "User exists"
else
	echo "User does not exist: Creating User"
	sudo useradd -m noah-adm
	sudo usermod -aG sudo noah-adm
	sudo passwd noah-adm
fi

#Install Git
block
if [[ $(command -v git) ]]; then
	echo "Git is Already installed, Moving On"
else
	echo "Installing Git"
	sudo sudo apt install git -y
fi
echo "Complete"

#Install DHCP Server
block
if [[ $(command -v isc-dhcp-server) ]]; then
	echo "isc DHCP is Already installed, Moving On"
else
	echo "Installing isc-DHCP"
	sudo apt install isc-dhcp-server -y
fi
echo "Complete"

#Download Repo
block
echo "Downloading Class Repo"

if [ -d "/home/noah-adm/Documents/TechNotes" ]; then
	echo "TechNotes are Already Downloaded, Moving On"
else
	sudo git -C /home/noah-adm/ clone https://github.com/CyPH3RSkULL5/TechNotes.git
fi 

echo "Complete"

#Check Hostname
block
echo "hostname is: " $(hostname) 
echo "---"

if [ "$(hostname)" = "dhcp01-noah" ]; then
	echo "Hostname Is Correct, Moving on"
else
	echo "hostname incorrect setting"
	hostnamectl set-hostname dhcp01-noah
	echo "New Hostname Set"
fi

#Copy DHCP Configs from downloaded Repo
block
echo "Backing Up DHCP config"
if [ -f "/var/www/html/index.html" ]; then
	echo "DHCPd.conf exists, backing it up"
	sudo mv /etc/dhcp/dhcpd.conf{,.backup}
	sudo rm /etc/dhcp/dhcpd.conf
	sudo cp /home/noah-adm/TechNotes/SEC-350/dhcpd.conf /etc/dhcp/
else
	echo "index.html NOT present, copying"
	sudo cp /home/noah-adm/TechNotes/SEC-350/dhcpd.conf /etc/dhcp/
fi
block

echo "Restarting Service"
sudo sudo systemctl restart isc-dhcp-server.service

echo $(sudo systemctl status isc-dhcp-server.service | grep Active)
echo "Complete"

block
echo "Copying Logging Config"
if [ -f "/etc/rsyslog.d/sec350-DHCPv.conf" ]; then
	echo "sec350-DHCPv.conf already exits, Replacing It"
	sudo rm sec350-DHCPv.conf
	sudo cp /home/noah-adm/TechNotes/SEC-350/sec350-DHCPv.conf /etc/rsyslog.d/
else
	echo "sec350-DHCPv.conf NOT present, copying"
	sudo cp /home/noah-adm/TechNotes/SEC-350/sec350-DHCPv.conf /etc/rsyslog.d/
fi

